Feature branch
normainobary2021/hello-world-4 pull request #1
Opened 2022-06-28 22:10 UTC by normainobary2021

2022-06-28 22:52 UTC, algerina requested changes
Hi @normainobary2021 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/neUaH5fz6ZpefE2KBP/giphy.gif"/>

## Highlights
- You have meaningful commits
- Your project looks good

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Adding a descriptive title and description to your pull request.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 22:52 UTC, algerina commented on README.md
> +
- [ ] Kindly Use the Microverse [template ](https://github.com/microverseinc/readme-template)for your Readme file, and Microverse Logo before the title and the author's social media links are missing.

2022-06-29 14:01 UTC, Ugboaja-Uchechi approved these changes
Hi @normainobary2021 , 

## STATUS APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Linters are passing ✔️ 
- Great commit messages ✔️ 
- Repo looks professional ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 14:01 UTC, Ugboaja-Uchechi commented on README.md
> +
- [ ] [OPTIONAL] Kindly remove all headers in the README that isn't necessary so your README can look more professional.

2022-06-29 14:01 UTC, Ugboaja-Uchechi commented on README.md
> +[Live Demo Link](https://livedemo.com)
- [ ] [OPTIONAL] Kindly remove the live demo since it isn't necessary for this project.

2022-06-29 16:54 UTC, normainobary2021 commented on README.md
> +
Alright please. Will do.

2022-06-29 17:01 UTC, merged